name: ${project.name}
main: de.redstoneworld.redplayerutils.RedPlayerUtils
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
commands:
   redplayerutils:
      aliases: [rpu]
      description: Main plugin command
      usage: /<command> [reload]
      permission: rwm.redplayerutils
      permission-message: You don't have the permission <permission>
   hunger:
      aliases: [redhunger]
      description: Give yourself or a player hunger
      usage: /<command> [<foodlevel>] [<player>]
   saturation:
      aliases: [redsaturation]
      description: Give yourself or a player saturation
      usage: /<command> [<saturationlevel>] [<player>]
   health:
      aliases: [redhealth, heal]
      description: Give yourself or a player health
      usage: /<command> [<healthlevel>] [<player>]
   xp:
      aliases: [redxp,experience,exp,redexp]
      description: Give yourself or a player experience
      usage: /<command> [<xp>] [<player>]
   level:
      aliases: [redlevel,lvl]
      description: Give yourself or a player level
      usage: /<command> [<level>] [<player>]
permissions:
   rwm.redplayerutils.use.self.hunger:
      description: Gives permission to use the /hunger command
      default: op
   rwm.redplayerutils.use.others.hunger:
      description: Gives permission to use the /hunger command on other players
      default: op
   rwm.redplayerutils.setlevel.self.hunger:
      description: Gives permission to set the food level
      default: op
   rwm.redplayerutils.setlevel.others.hunger:
      description: Gives permission to set the food level on other players
      default: op
   rwm.redplayerutils.use.self.saturation:
      description: Gives permission to use the /saturation command
      default: op
   rwm.redplayerutils.use.others.saturation:
      description: Gives permission to use the /saturation command on other players
      default: op
   rwm.redplayerutils.setlevel.self.saturation:
      description: Gives permission to set the saturation level
      default: op
   rwm.redplayerutils.setlevel.others.saturation:
      description: Gives permission to set the saturation level on other players
      default: op
   rwm.redplayerutils.use.self.health:
      description: Gives permission to use the /health command
      default: op
   rwm.redplayerutils.use.others.health:
      description: Gives permission to use the /health command on other players
      default: op
   rwm.redplayerutils.setlevel.self.health:
      description: Gives permission to set the health level
      default: op
   rwm.redplayerutils.setlevel.others.health:
      description: Gives permission to set the health level on other players
      default: op
   rwm.redplayerutils.use.self.xp:
      description: Gives permission to use the /xp command
      default: op
   rwm.redplayerutils.use.others.xp:
      description: Gives permission to use the /xp command on other players
      default: op
   rwm.redplayerutils.setlevel.self.xp:
      description: Gives permission to set the experience level
      default: op
   rwm.redplayerutils.setlevel.others.xp:
      description: Gives permission to set the experience level on other players
      default: op
   rwm.redplayerutils.use.self.level:
      description: Gives permission to use the /level command
      default: op
   rwm.redplayerutils.use.others.level:
      description: Gives permission to use the /level command on other players
      default: op
   rwm.redplayerutils.setlevel.self.level:
      description: Gives permission to set the elevelerience level
      default: op
   rwm.redplayerutils.setlevel.others.level:
      description: Gives permission to set the elevelerience level on other players
      default: op
   rwm.redplayerutils:
      description: Gives permission to the main plugin command
      default: op
   rwm.redplayerutils.reload:
      description: Gives permission to reload the config via /redplayerutils reload
      default: op